version: '3'

services:
  db:
    image: postgres:latest
    container_name: workwise-db
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=qdzJXw3xP3EXvwJiNwZH

  app:
    image: workwise
    container_name: workwise-app
    depends_on:
      - db
    ports:
      - '443:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      BASE_URL: ${BASE_URL}
      GOOGLE_APPLICATION_CREDENTIALS: /app/config/firebase.json
    volumes:
      - /Users/bulut/Documents/Repos/workwise/firebase.json:/app/config/firebase.json

volumes:
  postgres-data:
